---
- hosts: sandbox
  tasks:
    - name: Add an environment variable to the remote users shell
      lineinfile:
        dest: ~/.bash_profile
        regexp: "^ENV_VAR="
        line: "ENV_VAR=value"
        state: present
        backup: yes

    - name: get the value of the environment variable we added
      shell: "source ~/.bash_profile && echo $ENV_VAR"
      register: foo

    - name: print the environment variable
      debug:
        msg: "the variable is {{foo.stdout}} this job ran at: {{foo.start}} and finished at {{foo.end}}"
