---
- hosts: sandbox
  vars:
    pip_packages:
      - name: ansible-lint
        version: "5.0.7"
        get_version_command: "ansible-lint --version"
      - name: yamllint
        version: "1.9.0"
        get_version_command: "yamllint --version"

  tasks:
    - name: install python packages
      pip:
        name: "{{ item.name }}" 
        version: "{{ item.version }}"
      with_items: "{{ pip_packages }}"

      
    - name: run ansible lint version command and register variable
      command:
        cmd: "{{item.get_version_command}}"
      changed_when: false
      register: ansible_lint_version
      with_items: "{{ pip_packages }}"

    - name: print out item  
      debug:
        msg: "{{item.item}}"
      with_items: "{{ansible_lint_version.results}}"

    - name: print out item item
      debug:
        msg: "{{item.stdout}}"
      with_items: "{{ansible_lint_version.results}}"

      

      #- name: run yamllint version command and register variable
      #command:
      #  cmd: yamllint --version
      #register: yaml_lint_version
      #changed_when: false

      #- name: print yamllint version
      #debug:
      #  msg: "yamllint version: {{ yaml_lint_version }}"
