- hosts: sandbox
  tasks:
    - name: create file
      lineinfile:
        path: /home/ansible/serverinfo
        create: yes
        line: |
           hostname: "{{ ansible_hostname }}"
           IP Address(s): "{{ ansible_all_ipv4_addresses }}"
           OS Distro: "{{ansible_distribution }}" "{{ ansible_distribution_version }}" ("{{ ansible_distribution_release }}")
           date and time of generation: "{{ ansible_date_time.iso8601 }}"
